version: '3'

services: 

  app:
    image: quay.io/keycloak/keycloak:11.0.2
    container_name: micro-auth-app
    environment:
      # - DB_ADDR=database
      # - DB_VENDOR=postgres
      # - DB_DATABASE=services-auth
      # - DB_PORT=5432
      # - DB_USER=admin
      # - DB_PASSWORD=admin
      DB_ADDR: database
      DB_VENDOR: POSTGRES
      DB_DATABASE: services-auth
      DB_USER: admin
      DB_PASSWORD: admin
      # DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports: 
      - "8080:8080"
    depends_on: 
      - database

  database:
    build: .docker/postgres
    container_name: micro-auth-database
    tty: true
    environment:
      # - POSTGRES_DB=services-auth
      # - POSTGRES_USER=admin
      # - POSTGRES_PASSWORD=admin
      POSTGRES_DB: services-auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
