version: '3'

services: 

  app:
    # image: quay.io/keycloak/keycloak:11.0.2
    build: .
    container_name: micro-auth-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 300s /opt/jboss/tools/docker-entrypoint.sh
    environment:
      DB_ADDR: db
      DB_VENDOR: mysql
      DB_DATABASE: services-auth
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports: 
      - "8080:8080"
    depends_on: 
      - db

  db:
    build: .docker/postgres
    container_name: micro-auth-database
    tty: true
    environment:
      POSTGRES_DB: services-auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

  # db:
  #   build: .docker/mysql
  #   container_name: micro-auth-db
  #   tty: true
  #   environment:
  #     MYSQL_DATABASE: services-auth
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: root
  #   volumes:
  #     - ./.docker/dbdata:/var/lib/mysql
