version: '3'

services: 

  app:
    image: quay.io/keycloak/keycloak:11.0.2
    # build: .
    container_name: micro-auth-app
    # entrypoint: dockerize -wait tcp://db:5432 -timeout 300s /opt/jboss/tools/docker-entrypoint.sh
    environment:
      DB_ADDR: db
      DB_VENDOR: postgres
      DB_DATABASE: services_auth
      DB_USER: admin
      DB_PASSWORD: admin
      # DB_PORT: 5432
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports: 
      - "8080:8080"
    depends_on: 
      - db

  db:
    build: .docker/postgres
    container_name: micro-auth-database
    tty: true
    environment:
      POSTGRES_DB: services_auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

  # db:
  #   build: .docker/mysql
  #   container_name: micro-auth-db
  #   tty: true
  #   environment:
  #     MYSQL_DATABASE: services_auth
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_USER: admin
  #   volumes:
  #     - ./.docker/dbdata:/var/lib/mysql